### ISSUE TITLE
FP-Growth (progressive learning and serialization)

### ISSUE THREAD

**Issue by DJuego** [integeruser/FP-growth#2]
Thank you for your work!, @integeruser 

1) I was wondering if progressive learning is possible. I mean adding new data sets to the tree over time, instead recalculating everything from scratch.

2) If 1) is possible, I was wondering if it would be possible to add a serialization feature for storage (and recover) in a database or sending (and receiving) the tree. For example, with [cereal](https://github.com/USCiLab/cereal). 

Thanks!

P.S: Sorry for my English. :-(

**Comment by integeruser** [comment]
Hello again,

as I said it's been a while since I worked with FP-Growth and such, so I can't answer to 1). As for 2), I'd like to keep this repository as a simple reference implementation of the algorithm without any extra features.

**Comment by DJuego** [comment]
Ok. @integeruser. I understand it. Thank you for your answers and your work!

DJuego
