### ISSUE TITLE
Question: Data type

### ISSUE THREAD

**Issue by DJuego** [integeruser/FP-growth#3]
Question: I want to work with integers (in order to reduce the amount of memory needed). 
However I found in the code:

```cpp
`Item = std::string;`
```
Is it possible to change it safely? Should we change something else? Would the performance be affected?

Thanks!

**Comment by integeruser** [comment]
Hello,

yes, it should be possible to redefine `Item` without changing anything else in the code (of course the provided test cases won't work anymore). Regarding performances, I expect integers to beat strings but can't really tell without some tests, it's been a while since I used this algorithm.

**Comment by DJuego** [comment]
Ok. Thank you for your answer and your time, @integeruser!

DJuego
